#!/bin/sh -e
#
# Activate WIFI on Variscite VAR-SOM-AM62
#

. /etc/gpiochip

# Get gpiochip from main_gpio0 address
main_gpio0=$(get_gpiochip "600000.gpio")

# GPIO pin to supply 3.3V WIFI voltage
WIFI_3V3_GPIO="${main_gpio0} 54"

# GPIO pin to enable WIFI module
WIFI_EN_GPIO="${main_gpio0} 59"

# GPIO pin to enable BT module
BT_EN_GPIO="${main_gpio0} 60"

# GPIO pin to control routing of UART signals
# to BT module or SOM connector on DART-MX8M-MINI
BT_BUF_GPIO="${main_gpio0} 53"

# WIFI MMC host
WIFI_MMC_HOST=fa20000.mmc

SDHC_PLATFORM_DIR="/sys/bus/platform/drivers/sdhci-am654"

# Return true if WIFI interface exists
wifi_interface_exists()
{
	for i in $(seq 1 20); do
		if [ -d /sys/class/net/wlan0 ]; then
			return 0
		else
			sleep 1
		fi
	done

	return 1
}

# Bind WIFI device to MMC controller
wifi_mmc_bind()
{
	if [ -e ${SDHC_PLATFORM_DIR}/bind ]; then
		echo ${WIFI_MMC_HOST} > ${SDHC_PLATFORM_DIR}/bind
	fi
}

# Unbind WIFI device from MMC controller
wifi_mmc_unbind()
{
	if [ -e ${SDHC_PLATFORM_DIR}/${WIFI_MMC_HOST} ]; then
		echo ${WIFI_MMC_HOST} > ${SDHC_PLATFORM_DIR}/unbind
	fi
}

# Power up WIFI chip
wifi_up()
{
	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind

	# WIFI_3V3 up
	gpioset ${WIFI_3V3_GPIO}=1
	sleep 0.01

	# WLAN_EN up
	gpioset ${WIFI_EN_GPIO}=1

	# BT_EN up
	gpioset ${BT_EN_GPIO}=1

	# BT_BUF up
	gpioset ${BT_BUF_GPIO}=0

	# Wait at least 150ms
	sleep 0.2

	# BT_BUF down
	gpioset ${BT_BUF_GPIO}=1

	# BT_EN down
	gpioset ${BT_EN_GPIO}=0

	# Bind WIFI device to MMC controller
	wifi_mmc_bind

	# Load WIFI driver
	modprobe brcmfmac
}

# Power down WIFI chip
wifi_down()
{
	# Unload WIFI driver
	modprobe -r brcmfmac

	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind

	# WIFI_EN down
	gpioset ${WIFI_EN_GPIO}=0

	# BT_BUF down
	gpioset ${BT_BUF_GPIO}=1

	# BT_EN down
	gpioset ${BT_EN_GPIO}=0
	sleep 0.01

	# WIFI_3V3 down
	gpioset ${WIFI_3V3_GPIO}=0
}

# Return true if SOM has WIFI module assembled
wifi_is_available()
{
	# Read SOM options EEPROM field
	opt=$(i2cget -f -y 0x3 0x50 0x20)

	# Check WIFI bit in SOM options
	if [ $((opt & 0x1)) -eq 1 ]; then
		return 0
	else
		return 1
	fi
}

# Return true if WIFI should be started
wifi_should_not_be_started()
{
	# Do not start WIFI if it is not available
	if ! wifi_is_available; then
		return 0
	fi

	# Do not start WIFI if it is already started
	[ -d /sys/class/net/wlan0 ] && return 0

	return 1
}

# Return true if WIFI should not be stopped
wifi_should_not_be_stopped()
{
	# Do not stop WIFI if it is not available
	if ! wifi_is_available; then
		return 0
	fi

	return 1
}

# Start WIFI hardware
wifi_start()
{
	# Exit if WIFI should not be started
	wifi_should_not_be_started && exit 0

	# Try starting WIFI hardware
	for i in $(seq 1 3); do
		# Up WIFI
		wifi_up

		# Exit if WIFI interface exists
		wifi_interface_exists && exit 0

		# Down WIFI
		wifi_down

		# Wait enough time for discharge
		sleep 5
	done

	exit 1
}

# Stop WIFI hardware
wifi_stop()
{
	# Exit if WIFI should not be stopped
	wifi_should_not_be_stopped && exit 0

	# Down WIFI
	wifi_down
}

###########################
#  Execution starts here  #
###########################
case $1 in
start)
	wifi_start
	;;
stop)
	wifi_stop
	;;
esac

exit 0
